spring:
  datasource:
    url: jdbc:mariadb://localhost/root-ca-list
    #url: jdbc:h2:tcp://localhost/~/test;USER=sa;MODE=MySQL
    driverClassName: org.mariadb.jdbc.Driver
    username: dbuser
    password: dbuser
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      javax.persistence.validation.mode: none
